import type {Metadata} from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "PSDOWeb",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fr">
        <body
            className={"font-almarai"}
        >
        {children}
        </body>
        </html>
    );
}
